/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'data_acquisition'
 * Target:  'data_acquistion'
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/*
 * Define the Device Header File:
 */
#define CMSIS_device_header "LPC17xx.h"

/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.2.0 */
#define RTE_CMSIS_RTOS2          /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2 /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.2.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4 /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS /* RTOS FreeRTOS Timers */
/* Keil::CMSIS Driver:Ethernet MAC@2.14.0 */
#define RTE_Drivers_ETH_MAC0 /* Driver ETH_MAC0 */
/* Keil::CMSIS Driver:Ethernet PHY:DP83848C@6.2.0 */
#define RTE_Drivers_PHY_DP83848C /* Driver PHY DP83848C */
/* Keil::CMSIS Driver:USART@2.13.0 */
#define RTE_Drivers_USART0 /* Driver USART0 */
#define RTE_Drivers_USART1 /* Driver USART1 */
#define RTE_Drivers_USART2 /* Driver USART2 */
#define RTE_Drivers_USART3 /* Driver USART3 */
/* Keil::Device:Startup@1.0.0 */
#define RTE_DEVICE_STARTUP_LPC17XX /* Device Startup for NXP17XX */
/* Keil::Network&MDK:CORE@8.2.0 */
#define RTE_Network_Core /* Network Core */
/* Keil::Network&MDK:Interface:ETH@8.2.0 */
#define RTE_Network_Interface_ETH_0 /* Network Interface ETH 0 */

/* Keil::Network&MDK:Socket:UDP@8.2.0 */
#define RTE_Network_Socket_UDP /* Network Socket UDP */

#endif /* RTE_COMPONENTS_H */
